draw_sprite_ext(mask_index, image_index, x + hsp, y + vsp, 1, image_yscale, 0, image_blend, image_alpha)
draw_sprite_ext(sprite_index, image_index, x, y, xscale, image_yscale, 0, image_blend, image_alpha)
draw_set_font(Font1)
draw_set_color(c_white)
//draw_text(x, y - 50, move)